### ISSUE TITLE
Configure update option

### ISSUE THREAD

**Issue by brey** [ec-jrc/pyPoseidon#114]
This is a control on model building to exclude features such as update dem, meteo, etc. It's not fully integrated.

**Comment by pmav99** [comment]
The `if dem.exists()` line in oceamesh implies that `dem` is expected to be a `pathlib.Path` object on which they call the [`.exists()`](https://docs.python.org/3/library/pathlib.html#pathlib.Path.exists) method.

Instead of a `pathlib.Path` object you pass an `xarray.Dataset` object. That's why the exception gets thrown. 

If I remember well, `self.dem` is an instance of the `Dem` class which has an attribute named `Dataset` which is an instance of xarray Dataset. Check the other attributes and you may find a path to the DEM file. If there is such an attribute, pass that one to oceamesh. If the DEM has been downloaded from the internet then you may need to save it in a temporary file

**Comment by tomsail** [comment]
> If I remember well, `self.dem` is an instance of the `Dem` class which has an attribute named `Dataset` which is an instance of xarray Dataset. Check the other attributes and you may find a path to the DEM file. If there is such an attribute, pass that one to oceamesh. If the DEM has been downloaded from the internet then you may need to save it in a temporary file

that's why I am asking if it is really necessary. 
If `self.dem` is an xarray, why should `self.dem_source` (originary a path) be replaced by `self.dem `? 
Having both as xarray is redundant

**Comment by pmav99** [comment]
You will have to wait for @brey
